# Generated by Django 3.2.7 on 2022-05-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auctions.category'),
        ),
    ]
