# Generated by Django 3.2.8 on 2022-05-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_category_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bids',
        ),
    ]
